### ISSUE TITLE
FzfxBuffers does not switch buffer when current buffer unsaved even if vim.o.hidden is true

### ISSUE THREAD

**Issue by damanis** [linrongbin16/fzfx.nvim#421] opened 2023-11-21 09:11 UTC
When `vim.o.hidden` is `true` switching buffers should work without any question, but FzfxBuffers asks if continue or not.

**Comment by linrongbin16** [comment] 2023-11-21 09:20
the `ask if continue or not` is doing the check, if your current buffer is been modified.

since the actions is actually running vim command `edit! {filename}` to open the file, if current buffer is modified, the `edit!` will make you lose all your modifications.

**Comment by damanis** [comment] 2023-11-21 09:34
> do you mean that, you didn't modify current buffer

No, the buffer is modified. Internal command `:b <another buffer> works without prompt, since vim.o.hidden is set.

**Comment by linrongbin16** [comment] 2023-11-21 09:39
> > do you mean that, you didn't modify current buffer
> 
> No, the buffer is modified. Internal command `:b <another buffer>` works without prompt, since `vim.o.hidden` is set.

use `:buffer {filename}` could be a better method for `FzfxBuffers` actions.

I will update it.

**Comment by itsFrank** [comment] 2023-11-22 00:58
This issue sounds related, let me know if you would rather I open a new one.

I'm having a similar issue with `FzfxFiles`. I recently switch from fzf.vim which didn't have this behavior.

I very often have an modified unsaved buffer and use fzf to jump to other buffers and return (or eventually use `:wa`). With fzfx I get this y/n prompt even though my changes wouldn't be discarded. See video below for an example:

https://github.com/linrongbin16/fzfx.nvim/assets/7297152/6b0494db-f6a2-4ee7-bc5e-2b5239c8dbaf

Is there any way to disable the y/n prompt when switching files?

**Comment by linrongbin16** [comment] 2023-11-22 01:05
hi @itsFrank, @damanis, 

I think maybe I over-designed this behavior.

if we go back to fzf.vim behavior. e.g. use `edit {filename}` to open a file, and if you modified current buffer, directly throw the original vim error, just like I demo here: https://github.com/linrongbin16/fzfx.nvim/pull/365#issuecomment-1791923859.

will that be better? or there's any other solutions?

**Comment by itsFrank** [comment] 2023-11-22 01:15
I think your solution is fine and quite user friendly, but as the @damanis suggested, it may be as simple as adding a check for `vim.o.hidden`

I did this tiny change in a local fork of the plugin and it works great (`fzfx.nvim/lua/fzfx/ui.lua: line 10`):
```lua
-- from
  if utils.get_buf_option(bufnr, "modified") then
-- to
  if not vim.o.hidden and utils.get_buf_option(bufnr, "modified") then
```

**Comment by linrongbin16** [comment] 2023-11-22 01:30
> I think your solution is fine and quite user friendly, as @damanis suggested, it may be as simple as adding a check for `vim.o.hidden`
> 
> I did this tiny change in a local fork of the plugin and it works great (`fzfx.nvim/lua/fzfx/ui.lua: line 10`):
> 
> ```diff
> -  if utils.get_buf_option(bufnr, "modified") then
> +  if not vim.o.hidden and utils.get_buf_option(bufnr, "modified") then
> ```

Oh, thank you for point that out, I understand the point.

**Comment by linrongbin16** [comment] 2023-11-22 01:56
hi @itsFrank , @damanis  I had merged the fix PR https://github.com/linrongbin16/fzfx.nvim/pull/424 into main branch, please pull and try.

**Comment by itsFrank** [comment] 2023-11-22 01:58
FYI, I'm was checking to see if I could add a test for this new behavior, and I am not sure the ui tests are testing the function properly.

I modified the confirm test to look like this:
```lua
    it("confirm", function()
      vim.fn.feedkeys("i", "m")
      vim.fn.feedkeys("i", "m")
      vim.fn.feedkeys("i", "m")
      vim.fn.feedkeys("i", "m")

      local utils = require("fzfx.utils")
      print("is modified?: "..tostring(utils.get_buf_option(0, "modified")))

      local should_run = false
      ui.confirm_discard_buffer_modified(0, function()
        assert_true(should_run)
      end)
      should_run = true
      vim.fn.feedkeys("y", "m")
    end)
```

And it is failing, which means the callback runs before `vim.fn.feedkeys("y", "m")`. It also prints `is modified?: false`.

I would expect the callback to run only after `y` is sent?

**Comment by linrongbin16** [comment] 2023-11-22 02:00
@itsFrank  you are right, the unit testing is actually cover the test case....

**Comment by itsFrank** [comment] 2023-11-22 02:00
@linrongbin16 confirmed the fix worked on my end, thank you! Very fast!

**Comment by linrongbin16** [comment] 2023-11-22 02:01
> @linrongbin16 confirmed the fix worked on my end, thank you! Very fast!

The fix still not working on my personal nvim config, I'm looking into the reason now.

For the test case, I maybe make it better once I had more time (but since we tested it manually, I will lower the priority).

**Comment by linrongbin16** [comment] 2023-11-22 02:18
> > > do you mean that, you didn't modify current buffer
> > 
> > 
> > No, the buffer is modified. Internal command `:b <another buffer>` works without prompt, since `vim.o.hidden` is set.
> 
> use `:buffer {filename}` could be a better method for `FzfxBuffers` actions.
> 
> I will fix it.

Since `hidden` option is respect in prompt, this work can be cancelled (the `edit` command still works).

**Comment by damanis** [comment] 2023-11-22 06:09
@linrongbin16 
Confirm that the fix works.

**Comment by linrongbin16** [comment] 2023-11-22 06:55
thank you @damanis , I close this issue now.

**Closed by linrongbin16** 2023-11-22 06:55 UTC

**Comment by linrongbin16** [comment] 2023-11-23 03:47
> FYI, I'm was checking to see if I could add a test for this new behavior, and I am not sure the ui tests are testing the function properly.
> 
> I modified the confirm test to look like this:
> 
> ```lua
>     it("confirm", function()
>       vim.fn.feedkeys("i", "m")
>       vim.fn.feedkeys("i", "m")
>       vim.fn.feedkeys("i", "m")
>       vim.fn.feedkeys("i", "m")
> 
>       local utils = require("fzfx.utils")
>       print("is modified?: "..tostring(utils.get_buf_option(0, "modified")))
> 
>       local should_run = false
>       ui.confirm_discard_buffer_modified(0, function()
>         assert_true(should_run)
>       end)
>       should_run = true
>       vim.fn.feedkeys("y", "m")
>     end)
> ```
> 
> And it is failing, which means the callback runs before `vim.fn.feedkeys("y", "m")`. It also prints `is modified?: false`.
> 
> I would expect the callback to run only after `y` is sent?

Looking into this unit test issue again, I found there's a builtin function `setbufline` here: https://neovim.io/doc/user/builtin.html#setbufline().

Trying to use it to modify the buffer in unit test:

```lua
@@ -12,12 +12,22 @@ describe("ui", function()
  end)

  local ui = require("fzfx.ui")
  local utils = require("fzfx.utils")

  describe("[confirm_discard_buffer_modified]", function()
    it("confirm", function()
      vim.fn.feedkeys("i", "m")
      vim.fn.feedkeys("i", "m")
      vim.fn.feedkeys("i", "m")
      vim.fn.feedkeys("i", "m")

      vim.fn.setbufline(0, 1, "ui confirm")
      print(
        string.format(
          "test1 buffer is modified: %s\n",
          vim.inspect(utils.get_buf_option(0, "modified"))
        )
      )
      ui.confirm_discard_buffer_modified(0, function()
        assert_true(true)
      end)
@@ -28,6 +38,15 @@ describe("ui", function()
      vim.fn.feedkeys("i", "m")
      vim.fn.feedkeys("i", "m")
      vim.fn.feedkeys("i", "m")

      vim.fn.setbufline(0, 1, "ui confirm")
      print(
        string.format(
          "test2 buffer is modified: %s\n",
          vim.inspect(utils.get_buf_option(0, "modified"))
        )
      )

      ui.confirm_discard_buffer_modified(0, function()
        assert_true(true)
      end)
```

It still didn't work on my local develop machine (macOS), maybe try next time when we have other solutions.

cc @itsFrank  FYI.
