### ISSUE TITLE
Impossible configure preview window

### ISSUE THREAD

**Issue by damanis** [linrongbin16/fzfx.nvim#610] opened 2024-02-18 12:27 UTC
In v5.4.2 it is impossible to override preview-window to top for `buffers` and `files`.
The configuration (in `buffers` and `files` preview always shown on right, `live_grep` shown on top):
```
  local fzfx = require("fzfx")
  fzfx.setup({
    override_fzf_opts = {
        { "--preview-window", "top,75%" },
    },
    buffers = {
        fzf_opts = {
          { "--prompt",         "Buffers > " },
          { "--delimiter",      ":" },
          { "--preview-window", "top,75%,+{2}-/2" },
        },
    },
    files = {
        fzf_opts = {
          { "--prompt",         "Files > " },
          { "--delimiter",      ":" },
          { "--preview-window", "top,50%,+{2}-/2" },
        },
    },
  })
```
FZFX version: v5.4.2

**Comment by linrongbin16** [comment] 2024-02-18 13:10
This could be duplicated from #603, and also fixed by #609.

I will take a look later.

**Comment by linrongbin16** [comment] 2024-02-19 10:28
I think I know the root cause, will fix it later.

**Comment by linrongbin16** [comment] 2024-02-26 05:38
hi @damanis , I add 'top' and 'bottom' options in #612 , please pull main branch and try again!

**Comment by damanis** [comment] 2024-02-26 06:07
@linrongbin16 
Confirm, `top` works.
But size of preview panel (`75%` and `50%` in configuration above) are ignored. Is the way to set them?
P.S. Also, is there are options to configure Fzfx popup window size (e.g., 90% of the main window)?

**Comment by linrongbin16** [comment] 2024-02-26 06:09
> @linrongbin16 Confirm, `top` works. But size of preview panel (`75%` and `50%` in configuration above) are ignored. Is the way to set them? P.S. Also, is there are options to configure Fzfx popup window size (e.g., 90% of the main window)?

the size options `75%`/`50%` should work, let me check again.

**Comment by linrongbin16** [comment] 2024-02-26 06:27
hi @damanis , I take a look again, with the config you're using:

```lua
require("fzfx").setup({
    override_fzf_opts = {
        { "--preview-window", "top,75%" },
    },
    buffers = {
        fzf_opts = {
            { "--prompt", "Buffers > " },
            { "--delimiter", ":" },
            { "--preview-window", "top,75%,+{2}-/2" },
        },
    },
    files = {
        fzf_opts = {
            { "--prompt", "Files > " },
            { "--delimiter", ":" },
            { "--preview-window", "top,50%,+{2}-/2" },
        },
    },
})
```

The `override_fzf_opts` is force all popup (both `files` and `buffers`) using `--preview-window` = `top,75%`.

So you need to remove `override_fzf_opts`.

<img width="1920" alt="image" src="https://github.com/linrongbin16/fzfx.nvim/assets/6496887/05d0d796-3d04-4f3d-bf3c-9b2bcefdd60b">

**Closed by linrongbin16** 2024-02-26 06:27 UTC
