### ISSUE TITLE
Override configuration problem

### ISSUE THREAD

**Issue by damanis** [linrongbin16/fzfx.nvim#230] opened 2023-10-04 07:48 UTC
The problem with `FzfxLiveGrep <pattern> -- -g <file>`.
Without any configuration in my configs, after `lua require('fzfx').setup()` in nvim all work properly.
If I try override some default settings (change vertical layout to horizontal) in my init files:
```
if utils.isModuleAvailable("fzfx") then
  local fzfx = require("fzfx")
  local GroupConfig = require("fzfx.schema").GroupConfig
  fzfx.setup({
    live_grep = GroupConfig:make({
        fzf_opts = {
            { "--prompt",         "Live Grep > " },
            { "--delimiter",      ":" },
            { "--preview-window", "top,75%,+{2}-/2" },
        },
    }),
  })
end
```
the live grep works without `-- -g ...`, but does not find anything when I add glob argument.
As I see in fzfx code, this config, seems, should just override some default settings.

**Comment by damanis** [comment] 2023-10-05 06:02
@linrongbin16 
I taken it as is, but with same result.
Without overrides works properly. In log I see that `rg` command with `-g` options is made correct.

**Comment by linrongbin16** [comment] 2023-10-05 13:26
Hi @damanis , thanks for your report, it looks like the root cause is the `GroupConfig:make` API, it affect the `vim.tbl_deep_merge` behavior, so the merged configs lost some data.

**Comment by linrongbin16** [comment] 2023-10-05 13:28
I first add these `GroupConfig:make`, `CommandConfig:make`, `ProviderConfig:make` to try to simplify the configs (so people can write 1 single provider, 1 single previewer and 1 single command group), but now it looks somehow stupid, I will revert this design later.

**Comment by linrongbin16** [comment] 2023-10-05 13:33
It looks the only way to fix this issue at once is: copy and paste the whole group config of `live_grep`, which is of course stupid...

**Comment by linrongbin16** [comment] 2023-10-05 15:30
- #239 : drop 'ProviderConfig' class.

**Comment by linrongbin16** [comment] 2023-10-06 15:04
Hi @damanis , please add `--disabled` option to your config, then it will work.

See: https://github.com/linrongbin16/fzfx.nvim/pull/240/files#diff-390cfb09cd549ee50ecc1d31c004e6ec5b5000c3924f24ccc2d68d4c9c121bfd

**Comment by damanis** [comment] 2023-10-07 14:13
@linrongbin16 
It works! Thank you.

**Comment by damanis** [comment] 2023-10-07 14:16
@linrongbin16 
I added live grep in current buffer support.
May be you will find it useful (patch is not optimal, just copy/paste).
[buffer_live_grep.zip](https://github.com/linrongbin16/fzfx.nvim/files/12838010/buffer_live_grep.zip)

**Comment by linrongbin16** [comment] 2023-10-08 02:02
this is awesome, I think I can create a wiki page for advanced configuration, and add your case to it.

**Comment by damanis** [comment] 2023-10-08 06:15
> just double confirm: this patch is about to do live grep only on current buffer, correct?
Yes. It just limit live grep by current buffer.

**Closed** 2023-10-14 01:45 UTC
